
@host = http://127.0.0.1:5000/
@url1 = api/blogs
@url2 = api/blog
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY0Nzg1MjU1OSwianRpIjoiNmZiZjA5MWUtOTkyYy00ZmJlLTk0NTctMGM2NjQwMjVkZGRlIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InZuazEiLCJuYmYiOjE2NDc4NTI1NTksImV4cCI6MTY0Nzg1MzQ1OX0.JCdk_440EzyMf9XUpf2T6r1-_wSRZ67A3K__mGN5d4A
######################################
POST {{host}}/auth/signup
Content-Type: application/json

{
  "username": "vnk1",
  "email": "vnk1@vnk.com",
  "password": "password"
}
#####################################
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "vnk1",
  "password": "password"
}

#####################################
@token= eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY0Nzg2MjA4OCwianRpIjoiZjVmYjhkYjgtMWIyYS00ZjE0LTljZDUtN2Q4ZDA2NDNiMDMwIiwidHlwZSI6InJlZnJlc2giLCJzdWIiOiJ2bmsxIiwibmJmIjoxNjQ3ODYyMDg4LCJleHAiOjE2NTA0NTQwODh9.RjhDch2FvvH73RKA5tXOKjQ4iOTHWFze4tuxeTpkyPc
POST {{host}}/auth/refresh
Authorization: Bearer {{token}}

#####################################
GET {{host}}{{url1}}

################################
POST  {{host}}{{url1}}
Content-Type: application/json

{
  "title": "test2",
  "description": "test2"
}

################################

PUT  {{host}}{{url2}}/3
Content-Type: application/json

{
  "title": "test3",
  "description": "test3pqr"
}

###############################

GET  {{host}}{{url2}}/1
Authorization: Bearer {{token}}
###############################
DELETE {{host}}{{url2}}/1
